07-rails/solar_system/config/routes.rb
Rails.application.routes.draw do
  root :to => 'planets#index'
  get '/planets' => 'planets#index'
  get '/planets/new' => 'planets#new'
  post '/planets' => 'planets#create'
  get '/planets/:id' => 'planets#show', :as => 'planet'
  get '/planets/:id/edit' => 'planets#edit', :as => 'planet_edit'
  post '/planets/:id' => 'planets#update'
  post '/planets/:id/delete' => 'planets#destroy', :as => 'planet_delete'
end

07-rails/solar_system/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id       :integer          primary key
#  name     :text
#  image    :text
#  orbit    :float
#  diameter :float
#  mass     :float
#  moons    :integer
#

class Planet < ActiveRecord::Base
end

07-rails/solar_system/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

07-rails/solar_system/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def new
  end

  def create
    planet = Planet.create planet_params
    redirect_to planet_path(planet.id)
  end

  def show
    @planet = Planet.find params[:id]
  end

  def edit
    @planet = Planet.find params[:id]
  end

  def update
    planet = Planet.find params[:id]
    planet.update planet_params
    redirect_to planet_path(planet.id)
  end

  def destroy
    planet = Planet.find params[:id]
    planet.destroy # I AM GALACTUS
    redirect_to planets_path
  end

  private
  def planet_params
    # Strong parameters: a whitelisted set of permitted attributes (to fight evil)
    params.require(:planet).permit(:name, :image, :orbit, :diameter, :mass, :moons)
  end
end

07-rails/solar_system/app/helpers/planets_helper.rb
module PlanetsHelper
end

07-rails/solar_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SolarSystem</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <nav>
    <%= link_to "Home", root_path %>
    <%= link_to "New planet", planets_new_path %>
  </nav>

  <%= yield %>

</div>

</body>
</html>