07-rails/moma/config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
#     artists GET    /artists(.:format)          artists#index
#             POST   /artists(.:format)          artists#create
#  new_artist GET    /artists/new(.:format)      artists#new
# edit_artist GET    /artists/:id/edit(.:format) artists#edit
#      artist GET    /artists/:id(.:format)      artists#show
#             PATCH  /artists/:id(.:format)      artists#update
#             PUT    /artists/:id(.:format)      artists#update
#             DELETE /artists/:id(.:format)      artists#destroy
#       works GET    /works(.:format)            works#index
#             POST   /works(.:format)            works#create
#    new_work GET    /works/new(.:format)        works#new
#   edit_work GET    /works/:id/edit(.:format)   works#edit
#        work GET    /works/:id(.:format)        works#show
#             PATCH  /works/:id(.:format)        works#update
#             PUT    /works/:id(.:format)        works#update
#             DELETE /works/:id(.:format)        works#destroy
#

Rails.application.routes.draw do
  root :to => 'works#index'
  resources :artists
  resources :works
end

07-rails/moma/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :text
#  nationality :text
#  dob         :date
#  period      :text
#  image       :text
#  created_at  :datetime
#  updated_at  :datetime
#

class Artist < ActiveRecord::Base
  has_many :works
end

07-rails/moma/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  title      :text
#  year       :text
#  medium     :text
#  style      :text
#  image      :text
#  created_at :datetime
#  updated_at :datetime
#  artist_id  :integer
#

class Work < ActiveRecord::Base
  belongs_to :artist
end

07-rails/moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist
  end

  def show
    @artist = Artist.find params[:id]
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  private
  def artist_params
    params.require(:artist).permit(:name, :nationality, :dob, :period, :image)
  end
end

07-rails/moma/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all
  end

  def new
    @work = Work.new
  end

  def create
    work = Work.create work_params
    redirect_to work
  end

  def edit
    @work = Work.find params[:id]
  end

  def update
    work = Work.find params[:id]
    work.update work_params
    redirect_to work
  end

  def show
    @work = Work.find params[:id]
  end

  def destroy
    work = Work.find params[:id]
    work.destroy
    redirect_to works_path
  end

  private
  def work_params
    params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
  end
end

07-rails/moma/app/helpers/artists_helper.rb
module ArtistsHelper
end

07-rails/moma/app/helpers/works_helper.rb
module WorksHelper
end

07-rails/moma/app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <fieldset>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </fieldset>
  <fieldset>
    <%= f.label :nationality %>
    <%= f.text_field :nationality %>
  </fieldset>
  <fieldset>
    <%= f.label :dob, "Date of birth" %>
    <%= f.text_field :dob, :placeholder => "YYYY-MM-DD" %>
  </fieldset>
  <fieldset>
    <%= f.label :period %>
    <%= f.text_field :period %>
  </fieldset>
  <fieldset>
    <%= f.label :image %>
    <%= f.url_field :image %>
  </fieldset>

  <fieldset>
    <label></label>
    <%= f.submit %>
  </fieldset>
<% end %>

07-rails/moma/app/views/artists/edit.html.erb
<h1>Edit Artist</h1>

<%= render :partial => 'form' %>

07-rails/moma/app/views/artists/index.html.erb
<h1>Artists</h1>
<% @artists.each do |artist| %>
  <%= image_tag artist.image, :class => 'thumb' %>
  <ul>
    <li><%= link_to artist.name, artist %></li>
    <li><%= artist.nationality %></li>
    <li><%= artist.dob.strftime "%A, %e %B, %Y" %></li>
    <li><%= artist.period %></li>
  </ul>
<% end %>

07-rails/moma/app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render :partial => 'form' %>

07-rails/moma/app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

<%= image_tag @artist.image, :class => 'feature' %>
<ul>
  <li><%= @artist.name %></li>
  <li><%= @artist.nationality %></li>
  <li><%= @artist.dob.strftime "%A, %e %B, %Y" %></li>
  <li><%= @artist.period %></li>
</ul>

<div class="controls">
  <%= link_to "Edit artist", edit_artist_path(@artist) %>
  <%= link_to "Delete artist", @artist, :method => 'delete', :data => { :confirm => "Are you sure?" } %>
</div>

<% @artist.works.each do |work| %>
  <%= link_to image_tag(work.image, :class => 'thumb'), work %>
<% end %>